#Updated configuration
#Mon Feb 09 05:49:41 UTC 2026
//PASSWORD=Test12345(
URLTESTQA2=https\://qa2.bsbu-bmsdev.com/admin/
USERNAMEQA2=nishikant.wandhare@yopmail.com
THINKTIME=3000
URLTEST=https\://perf.bsbu-bmsdev.com/admin/
USERNAME=vivek.sharma11@yopmail.com
//URLTEST=https\://smoketest.a1e76901c2b94f088862.centralindia.aksapp.io/customer/accessmanagement
PATHCHROMEDRIVER=C\:\\Users\\azureuser\\Desktop\\BSBU\\Driver\\chromedriver-win64\\chromedriver.exe
DelAccount2=Performance Account Web16
DelAccount3=Performance Account Web17
DelAccount4=Performance Account Web18
DelAccount5=Performance Account Web19
Account13=Performance Account Web13
Account12=Performance Account Web12
Account11=Performance Account Web11
Account10=Performance Account Web10
//URLTESTADMIN=https\://perf.bsbu-bmsdev.com/admin/
//USERNAME=ankusha4@yopmail.com
Account5=Performance Account Web5
Account6=Performance Account Web6
Account7=Performance Account Web7
Account8=Performance Account Web8
PASSWORD=Glob@23456789
AFTERCLICKTHINKTIME=5000
Account9=Performance Account Web9
AccountUpdated=Performance Account Web18
CREDENTIAL=123456789012
TIMEOUT=30
Account14=Performance Account Web14
Account1=Performance Account Web01
Account2=Performance Account Web2
Account3=Performance Account Web3
Account4=Performance Account Web4
DelAccount1=Performance Account Web15
